"""
Schema definitions for AI-generated Kubernetes rule candidates.
"""
from dataclasses import dataclass
from typing import List

@dataclass
class RuleCandidate:
   """
   Represents a Kubernetes rule generated by AI
   and awaiting human approval.
   """
   pattern: str
   root_cause: str
   severity: str
   confidence: str
   explanation: str
   recommendations: List[str]
   commands: List[str]

   source: str = "Gemini AI"
   status: str = "candidate"
   created_at: str = ""
   approved_at: str = ""
   promoted_at: str = ""